### ISSUE TITLE
psattack builder fails on first run

### ISSUE THREAD

**Issue by macubergeek** [jaredhaight/PSAttack#13]
Ran PSbuilder tool and it failed with this error:

Unhandled Exception: System.Net.WebException: The remote server returned an erro
r: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at PSAttack.Utils.PSAUtils.DownloadFile(String url, String dest)
   at PSAttack.Program.Main(String[] args)

**Comment by jaredhaight** [comment]
Hrm, can you get me the full output from the screen? It would be helpful to see what it was trying to download.

Thanks!

**Comment by macubergeek** [comment]
Ok here is the problem. I can compile PSAttack and PSAttackBuilder just fine. PSAttack seems to work fine BUT when I run PSAttackBuilder it errors out. Below is the error I'm getting.
Version 1.0


Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\James Kelly\Desktop\modules.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare sha
re, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongP
ath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOption
s options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize
, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at PSAttackBuildTool.Program.Main(String[] args)

**Comment by jaredhaight** [comment]
Hey macubergeek, 

Nothing you're doing wrong here, totally a bug. I mentioned this in the [the issue you opened under the buildtool today](https://github.com/jaredhaight/PSAttackBuildTool/issues/4), this is because the build tool is choking on the space in the file path. Should be an easy fix!

Precompiled versions of both PSAttack and the build tool are available on the releases tab of their respective projects page, which you can use in the mean time. Here are the links:

https://github.com/jaredhaight/PSAttack/releases
https://github.com/jaredhaight/PSAttackBuildTool/releases

I'm going to go ahead and close this issue and we can just work off [the issue under the build tool](https://github.com/jaredhaight/PSAttackBuildTool/issues/4).

Thanks for submitting this!
