### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException:

### ISSUE THREAD

**Issue by ronnieflip** [jaredhaight/PSAttack#27]
Am running into this error, what would be the problem.

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\#553m134ty4-jnr\Desktop\PowerOPS-1.0-beta\modules.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at PSAttackBuildTool.Program.Main(String[] args)

**Comment by ronnieflip** [comment]
My bad, figured this out.
