### ISSUE TITLE
System.Security.Cryptography.RijndaelManaged..ctor()

### ISSUE THREAD

**Issue by JamesMuse** [jaredhaight/PSAttack#31]
I am getting this error when trying to run .\PSAttack.exe from inside a powershell window.  

Loading...

Unhandled Exception: System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic a
lgorithms.
   at System.Security.Cryptography.RijndaelManaged..ctor()
   at PSAttack.Utils.CryptoUtils.DecryptFile(Stream inputStream)
   at PSAttack.Program.PSInit()
   at PSAttack.Program.Start.launchPSAttack()
   at PSAttack.Program.Main(String[] args)

**Comment by JamesMuse** [comment]
Found this article which may help  https://blogs.msdn.microsoft.com/cdndevs/2011/02/22/crypto-craziness-meeting-fips-requirements-with-managed-code/

**Comment by jaredhaight** [comment]
Ahh, that makes sense. *Should* just be able to switch to a FIPS compliant encryption here. Tagging this for a 2.0 release.
