### ISSUE TITLE
The handle is invalid

### ISSUE THREAD

**Issue by hexrunner** [jaredhaight/PSAttack#32]
Running PSAttack on Windows 8.1 as low privileged user.
After decrypting PSAttack Get-Attack it throws an unhandled exception.
Any idea?

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at PSAttack.Program.PSInit()
   at PSAttack.Program.Start.launchPSAttack()
   at PSAttack.Program.Main(String[] args)

**Comment by asfakiana** [comment]
got the same as an admin in Win10

**Comment by jaredhaight** [comment]
Thats really strange. How did you execute PSAttack? Just downloaded it and doubleclicked? Are you running through a command prompt?
